---
title: "models"
author: "Djebari"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#here use cross validation to choose between the SVD, SVDF and ALS for implicit feedback 
```{r}
set.seed(13)
scheme <- evaluationScheme(real_ratings, 
                           method="cross", 
                           k = 5,
                           given = 2,
                           goodRating = 3,
                           train = 0.8)

scheme


algorithms <- list("SVD" = list(name="SVD", param=list(k = 50, normalize = "Z-score")),
                   "Funk_SVD" = list(name = "SVDF", 
                                     param = list(k = 10, normalize = "Z-score",
                                                  min_epochs = 50, max_epochs = 100,verbose = TRUE)),
                   "ALS_implicit" = list(name="ALS_implicit", 
                      param = list(lambda=0.1, alpha = 0.5, n_factors=50, 
                                   n_iterations=5, seed = 13, verbose = TRUE)))


results <- evaluate(scheme, algorithms, type = "topNList", n  = c(1, seq(4, 20, 4)))

```

#results
## SVD
```{r}
results$SVD %>% 
  getConfusionMatrix() %>% 
  map_df(~as.data.frame(.) %>% rownames_to_column()) %>%
  group_by(rowname) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(x = FPR, y = TPR)) +
  geom_line() +
  geom_point(shape = 21, fill = "skyblue", size = 2.5) +
  #scale_x_continuous(limits = c(0, 0.0025)) +
  labs(title = "ROC Curve",
       x = "False Positive Rate", 
       y = "True Positive Rate",
       subtitle = "method : SVD") +
  geom_label(aes(label = rowname)) +
  theme_minimal()
```

## FUNK SVD
```{r}
results$Funk_SVD %>% 
  getConfusionMatrix() %>% 
  map_df(~as.data.frame(.) %>% rownames_to_column()) %>%
  group_by(rowname) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(x = FPR, y = TPR)) +
  geom_line() +
  geom_point(shape = 21, fill = "skyblue", size = 2.5) +
  #scale_x_continuous(limits = c(0, 0.0025)) +
  labs(title = "ROC Curve",
       x = "False Positive Rate", 
       y = "True Positive Rate",
       subtitle = "method : FUNK SVD") +
  theme_minimal()
```
## ALS
```{r}
results$ALS_implicit %>% 
  getConfusionMatrix() %>% 
  map_df(~as.data.frame(.) %>% rownames_to_column()) %>%
  group_by(rowname) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(x = FPR, y = TPR)) +
  geom_line() +
  geom_point(shape = 21, fill = "skyblue", size = 2.5) +
  #scale_x_continuous(limits = c(0, 0.0025)) +
  labs(title = "ROC Curve",
       x = "False Positive Rate", 
       y = "True Positive Rate",
       subtitle = "method : ALS") +
  theme_minimal()
```


```{r}
results$SVD@results %>% 
  map_df(function(x) x@cm %>% 
           as.data.frame %>%
           rownames_to_column("n")) %>% 
  group_by(n) %>%
  summarise_all(mean) %>%
  mutate(n = as.numeric(n)) %>%
  arrange(n) %>% 
  rename("Top-N" = n)


results$Funk_SVD@results %>% 
  map_df(function(x) x@cm %>% 
           as.data.frame %>%
           rownames_to_column("n")) %>% 
  group_by(n) %>%
  summarise_all(mean) %>%
  mutate(n = as.numeric(n)) %>%
  arrange(n) %>% 
  rename("Top-N" = n)


results$ALS_implicit@results %>% 
  map_df(function(x) x@cm %>% 
           as.data.frame %>%
           rownames_to_column("n")) %>% 
  group_by(n) %>%
  summarise_all(mean) %>%
  mutate(n = as.numeric(n)) %>%
  arrange(n) %>% 
  rename("Top-N" = n)
```

```{r}
results$SVD %>% 
  getConfusionMatrix() %>% 
  map_df(~as.data.frame(.) %>% rownames_to_column()) %>%
  group_by(rowname) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(x = recall, y = precision)) +
  geom_line() +
  geom_point(shape = 21, fill = "skyblue", size = 2.5) +
  labs(title = "Precision-Recall Curve",
       x = "Recall", y = "Precision",
       subtitle = "method : SVD") +
  theme_minimal()
```

```{r}
results$Funk_SVD %>% 
  getConfusionMatrix() %>% 
  map_df(~as.data.frame(.) %>% rownames_to_column()) %>%
  group_by(rowname) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(x = recall, y = precision)) +
  geom_line() +
  geom_point(shape = 21, fill = "skyblue", size = 2.5) +
  labs(title = "Precision-Recall Curve",
       x = "Recall", y = "Precision",
       subtitle = "method : Sunk SVD") +
  theme_minimal()
```

```{r}
results$ALS_implicit %>% 
  getConfusionMatrix() %>% 
  map_df(~as.data.frame(.) %>% rownames_to_column()) %>%
  group_by(rowname) %>% 
  summarise_all(mean) %>% 
  ggplot(aes(x = recall, y = precision)) +
  geom_line() +
  geom_point(shape = 21, fill = "skyblue", size = 2.5) +
  labs(title = "Precision-Recall Curve",
       x = "Recall", y = "Precision",
       subtitle = "method : ALS") +
  theme_minimal()
```

```{r}
get_error <- function(x){
x %>% 
  map(function(x) x@cm) %>% 
  unlist() %>% 
  matrix(ncol = 3, byrow = T) %>% 
  as.data.frame() %>% 
  summarise_all(mean) %>% 
  setNames(c("RMSE", "MSE", "MAE"))
}

get_recap <- function(x){
  x %>% 
    getConfusionMatrix() %>% 
    map_df(~as.data.frame(.) %>%
             rownames_to_column("n")) %>%
    group_by(n) %>% 
    summarise_all(mean)
}

```


```{r}
result_eval <- map2_df(.x = results, 
                       .y = c("SVD", "Funk_SVD", "ALS_implicit"), 
                       .f = function(x, y) x %>% get_recap() %>% mutate(method = y)
                       ) 

result_eval

result_eval %>% 
  ggplot(aes(x = FPR, y = TPR, color = method)) +
  geom_line() +
  geom_point() +
  labs(title = "ROC Curve", color = "Method",
       y = "True Positive Rate", x = "False Positive Rate") +
  theme_minimal() +
  theme(legend.position = "top")
```

# the final model
```{r}
ALS_eval_recommender <- Recommender(data = getData(scheme, "train"),method = 'ALS_implicit',
                                    parameter = list(lambda=0.1, alpha = 0.5, n_factors=50, n_iterations=5, seed = 13, verbose = TRUE))
                              

ALS_eval_prediction <- predict(object = ALS_eval_recommender, newdata =getData(scheme, "known"), n = 5, type = "ratings")

ALS_eval_accuracy <- calcPredictionAccuracy(x = ALS_eval_prediction, data = getData(scheme, "unknown"), byUser =TRUE)

head(ALS_eval_accuracy)

ALS_eval_prediction <- predict(object = ALS_eval_recommender, newdata =getData(scheme, "known"), n = 5, type = "topNList")

ALS_eval_prediction@items
getList(ALS_eval_prediction)
```


#### saving 

```{r}
#saveRDS(results, "results.rds")
#saveRDS(result_error, "result_error.rds")
#saveRDS(result_eval, "result_eval.rds")
#saveRDS(recom_svdf, "recom_svdf.rds")
#saveRDS(recom_svd, "recom_svd.rds")
#saveRDS(recom_als, "recom_als.rds")
#SaveRDS(recc_predicted_als, "recc_predicted_als.rds")
#SaveRDS(recc_predicted_svdf, "recc_predicted_svdf.rds")
#SaveRDS(recc_predicted_svd, "recc_predicted_svd.rds")
```
